# Generated by Django 3.1.4 on 2020-12-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('img_url', models.SlugField(max_length=255)),
                ('src_url', models.SlugField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('duration', models.FloatField()),
                ('repr_duration', models.CharField(default='0:00', max_length=10)),
            ],
        ),
    ]
