# Generated by Django 3.1.4 on 2020-12-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flavaudio', '0002_auto_20201225_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='img_url',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='audio',
            name='src_url',
            field=models.CharField(max_length=255),
        ),
    ]
