# Generated by Django 3.1.4 on 2020-12-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flavplaylist', '0001_initial'),
        ('flavaudio', '0003_auto_20201225_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='playlists',
            field=models.ManyToManyField(to='flavplaylist.Playlist'),
        ),
    ]
