# Generated by Django 3.1.4 on 2020-12-25 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flavaudio', '0004_audio_playlists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='playlists',
        ),
    ]
